name: joja_bdl
description: Application mobile JOJA DISTRIBUTION - Bons de Livraison
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.0.0

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.0                        # Client HTTP pour l'API REST
  shared_preferences: ^2.3.0          # Stockage local (token, user info)
  speech_to_text: ^7.0.0              # Reconnaissance vocale
  hand_signature: ^3.0.3              # Canvas signature
  connectivity_plus: ^6.0.0           # Verifier la connexion internet
  path_provider: ^2.1.0               # Acces au systeme de fichiers
  url_launcher: ^6.2.0                # Ouvrir des URLs
  intl: ^0.19.0                       # Formatage dates en francais

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
